### ISSUE TITLE
How to tell / log when offline tasks fail or fail to run

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#100]
Related to this:

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/95#issuecomment-205569524

On `bi-1` I just re-edited that venue ID 370165697 (and changed `Poo Men` to `Poo Man`) and hit the save button. Both ES and the local file system are updated but the change is not pushed to the GitHubs.

https://github.com/whosonfirst-data/whosonfirst-data-venue-us-new-york/commits/master

```
cat /usr/local/mapzen/whosonfirst-data-venue-us-new-york/data/370/165/697/370165697.geojson | grep 'wof:name'
    "wof:name":"Poo Man",
```

**Comment by thisisaaronland** [comment]
Speaking of poo...

![screen shot 2016-04-05 at 12 34 21](https://cloud.githubusercontent.com/assets/12658759/14295494/c68a2694-fb2a-11e5-8823-f1e8f02d7db6.png)

**Comment by dphiffer** [comment]
Oddly I cannot reproduce this one—after reverting the name back to "Poo Men" it seems that [GitHub](https://github.com/whosonfirst-data/whosonfirst-data-venue-us-new-york/commit/8204ede2b5c916a63d6bbe939c268a383182eeab) and [ES](https://52.91.189.86/search/?q=poo) got their updates.

But I totally agree with the underlying premise that we need to account for the Gearman worker failure mode. I have some ideas for how this might work that I'll work on this morning.

**Comment by thisisaaronland** [comment]
Are you testing locally or on `bi-1` ?

**Comment by dphiffer** [comment]
I've been testing locally quite a bit, but the Poo Test I mentioned was on `bi-1`. Wonder if there's some other factor involved?
