### ISSUE TITLE
Move properties_lookup.json into its own repo

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#138]
This file over here:
https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/master/www/meta/properties_lookup.json

And pull it down from the Makefile. Also, add a command line argument to use the mapping in `wof-csv-to-feature-collection` and elsewhere.

**Comment by thisisaaronland** [comment]
`whosonfirst-qgis` ?

**Comment by nvkelso** [comment]
`whosonfirst-property-aliases`?
`whosonfirst-slim-properties`?

On Tue, Jun 14, 2016 at 2:35 PM, Aaron Straup Cope <notifications@github.com

**Comment by thisisaaronland** [comment]
That settles it – they (one or more JSON files) should go in an aliases folder in the `whosonfirst-properties` repo.

**Comment by dphiffer** [comment]
See also:
https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/commit/a8b40844aa0ae9ecdbdb678f126f8dfbc2ceddc9
https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/300fc4c30cbf5fe1343a583d73191621700e35e8
