### ISSUE TITLE
Add option to update or replace an existing geometry

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-www-boundaryissues#142]
Looking over the SF neighbourhoods post it sounds like a common use case we should support is uploading a NEW geometry (from a new / different source), not just updating an existing geometry shape.

If replace, automatically move the current geom to an alt, add new source for the new geom (prompting the user to choose existing source or create a new source).

/cc @stepps00

**Comment by thisisaaronland** [comment]
I have been thinking about geometries. Increasingly I am thinking the easiest / best thing is to create an "alt" geometry file for every single source, including the so-called default/consensus geometry. If the default and an alt file are the same that can be derived by way of their `geom_hash`.

This will potentially increase the size of any one WOF repo significantly so one possible solution would be to move all the alt geometries in to a separate repository. This would precipitate a fair amount of hoop-jumping trying to keep track of where to write files so I am not super excited about the idea...

**Comment by stepps00** [comment]
I agree, we should have the option for new geometry uploads while preserving the original geometry.

I'm also not incredibly excited about the idea of a separate repo for alt-geometries, but depending on how often we import new geometries, it could be a better solution than adding many, many alt-geometries to our `wof-data` repo.. worth discussing our options.

**Comment by thisisaaronland** [comment]
Done!
