### ISSUE TITLE
PLEASE TO NEVER NEVER NEVER SET `Flask.app.debug` TO TRUE

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#15]
https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/0c785480c96f9556c295ad721f92216b1a977971#diff-c2ffb1a88703bec41828e725aa851b88R21

This is a security nightmare waiting to happen. See also: Patreon.

Can you fix this (basically right now :-) so that it doesn't fall through the cracks.

**Comment by dphiffer** [comment]
I should get better at closing these things using the GitHub hooks. (Fixed!)
