### ISSUE TITLE
Ensure Boundary Issues tool can handle neighbourhood updates

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#154]
/ @nvkelso  We've recently updated Who's on First neighbourhood records in Seattle and San Francisco and have several .geojson files ready for import for each market. The .geojson files will be uploaded to this issue in compressed files - let's make sure the Boundary Issues tool is able to ingest these files appropriately.

**Comment by stepps00** [comment]
Here are the [San Francisco neighbourhood files](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/files/391602/SanFrancisco_NeighbourhoodUpdates.zip).

**Comment by thisisaaronland** [comment]
Too soon. This hasn't even been fully tested from the command line.

**Comment by thisisaaronland** [comment]
Closing because this is now part of https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/309
