### ISSUE TITLE
Display more/all properties

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#158]
This is related (in a way) to issue #54 and part of the larger work around properties in general – https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues?q=is%3Aopen+is%3Aissue+label%3Aproperties – but I discovered this interesting bug today:

I can not edit (or add) `wof:country` because it's already defined but not displayed in the UI.

![screen shot 2016-08-10 at 15 14 49](https://cloud.githubusercontent.com/assets/12658759/17573289/412b35b8-5f0e-11e6-986b-b0c216e530ad.png)

**Comment by dphiffer** [comment]
This should be fixed. In the case of `wof:country`, the property was actually on the page but just hidden using CSS. There were a handful of other ones I made visible too. I think the only ones that are still hidden are `wof:breaches` and `wof:belongsto`.
