### ISSUE TITLE
{...|@escape} all template variables.

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#16]
Just assume template variables are trying to kill you.

For example: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/5ec4f22e1951c7887a9e9c9976bc21a389ef165e

**Comment by dphiffer** [comment]
Closed by https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/2798dd6162f7bde9b62a25879f93433817d8423e
