### ISSUE TITLE
Missing add new k/v pair form elements

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#160]
Tried to add `addr:website` to this record but there are no input elements – 

https://whosonfirst.mapzen.com/boundaryissues/ca/id/572188969/

**Comment by dphiffer** [comment]
Fixed!

**Comment by thisisaaronland** [comment]
Deployed?

**Comment by dphiffer** [comment]
Yeah, are you not seeing the change?

**Comment by thisisaaronland** [comment]
I am now. Dunno...
