### ISSUE TITLE
BI not capturing mz:categories

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#165]
Assigned `shop_and_service:service=design_studio` in the UI but it doesn't seem to be sticking in the save/processing flow.

https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/c97641f6400914f2bc9f1611f4a1601cc287c5b5

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-venue-us-ca/c97641f6400914f2bc9f1611f4a1601cc287c5b5/data/907/212/647/907212647.geojson

![screen shot 2016-08-12 at 11 15 11](https://cloud.githubusercontent.com/assets/12658759/17632596/20186faa-607e-11e6-92b8-6f9b6d47cc36.png)

**Comment by thisisaaronland** [comment]
Bumping this one as it will the source of constant confusion/frustration as more people start using BI. For example:

https://whosonfirst.mapzen.com/boundaryissues/ca/id/907214327/
https://whosonfirst.mapzen.com/boundaryissues/ca/id/907214327.geojson

**Comment by dphiffer** [comment]
Fixed!

See also: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/1eec65b3fcff7524afefef54ed94b3067a89c113
