### ISSUE TITLE
BI incorrectly encoding wof:concordances

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#169]
Empty concordances are encoded as a list rather than a dictionary.

https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/5bfc5ce6c30c373669db41bc4f8c43add8f2d53a

![screen shot 2016-08-21 at 13 27 27](https://cloud.githubusercontent.com/assets/12658759/17839652/2926ddda-67a3-11e6-85b0-bddff639444f.png)

**Comment by dphiffer** [comment]
This one is surprising, because in theory I'd fixed it here:
https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/d4fa97be12b4c7e940ba30770cad0b8c0481892c#diff-d5b35fc0af089bef41f9d2c88d5f183bR1010

I just tried saving that record again and it _appears_ to have done the right thing (i.e., `wof:concordances: {}`). It's possible there was just an old version of the JS cached...

**Comment by thisisaaronland** [comment]
Hrm, okay we should ensure that all the JS libraries have a cache-busting query param appended to them. The easiest thing is just to define a var in the global config and append it in `inc_head` or equivalent.

**Comment by dphiffer** [comment]
Yeah, good point, I'll do that. But it looks like the test I just ran didn't actually fix the record, so something is definitely up.

Like, here is the request from the encoded GeoJSON...
<img width="846" alt="screen shot 2016-08-22 at 6 51 58 pm" src="https://cloud.githubusercontent.com/assets/38114/17874676/3f478620-689b-11e6-8a7f-59ca1b4510af.png">

And then when that gets published, it ends up [leaving out the change](https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/cb6fe3e4b331ec63989723df46076166181e414c).

**Comment by dphiffer** [comment]
Oh, I think I know why my test failed. When I'm calculating the diff, PHP can't tell the difference between an empty array and an empty _associative array_. So it doesn't see that as a changed property. I am going to add, then remove, a single concordance and see if it reverts back.

**Comment by dphiffer** [comment]
Ok, looks like this is fixed now.
https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/1868f185f9117737d2dc3e6adf29d79ea38f0cfb

**Comment by dphiffer** [comment]
Reopening because it seems to have cropped up with `mz:hours` getting misencoded: https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ny/commit/5e9b027a0c1a37dacd3d135aae5ba532d4d86bed

Thanks to @stepps00 for catching that.

**Comment by dphiffer** [comment]
Closing this in favor of #318.
