### ISSUE TITLE
supersedes/superseded_by still not sticking

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#170]
https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-venue-us-ca/master/data/354/091/727/354091727.geojson

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-venue-us-ca/master/data/907/219/085/907219085.geojson

`907219085` should supersede `354091727` – I did this in BI but the changes were not applied, or they were applied but then removed during a later edit.

**Comment by dphiffer** [comment]
Ok, this should be fixed now. It took me a while to figure it out, but it's about a :facepalm: level 8:
https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/abb74bb4a37d4bab254dfa6602c938a333866b1d

And here's an update that fixes those supersedes/superseded_by properties:
https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/3a360247369a38ebd9db5db9a1ea0cba96ceaf15

**Comment by thisisaaronland** [comment]
:D
