### ISSUE TITLE
Missing hours prevents new places from being added

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#188]
![screen shot 2016-09-19 at 11 02 23](https://cloud.githubusercontent.com/assets/12658759/18643204/e6bfd1a0-7e58-11e6-8055-b6db387e9493.png)

Note - there is no "hours" UI when adding a place.

**Comment by dphiffer** [comment]
Fixed the part that made saving stop working, but it seems like this also points to a problem with how error reporting works on the add template.
