### ISSUE TITLE
Recent commit through Boundary Issues is not reflected in Spelunker records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#189]
[This commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/68300dda3f75531dca1937b5fe232eee83d36ab6) was made through the admin Boundary Issues tool on Sept. 15th. 

When searching the Spelunker to view any of these updated records, the changes are not reflected.

**Comment by thisisaaronland** [comment]
Closing because this was so long ago who knows what was going on, at the time...
