### ISSUE TITLE
Adding new venues is broken

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#198]
For some reason BI is not seeing (or setting) the `geom:latitude` or `geom:longitude` fields so when you click save you get this error:

![screen shot 2016-10-17 at 18 23 28](https://cloud.githubusercontent.com/assets/12658759/19461159/127a70bc-9497-11e6-9549-cb6d0e2b1330.png)

If you manually add them via the "add a new field" buttons you can make the error go away.

**Comment by dphiffer** [comment]
Weird, I'll take a look.

**Comment by dphiffer** [comment]
Couldn't reproduce this one, is it repeatable for you?
