### ISSUE TITLE
Re-enable notifications

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#204]
Notifications are presently [turned off](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/43a82cc5979ec9db583f9e5cbdf48549955d6ea6), until we can figure out websockets.

Probably this will require [upgrading nginx](https://www.nginx.com/resources/admin-guide/proxy-protocol/) on the whosonfirst-proxy machine so it can use `proxy_protocol`.

**Comment by thisisaaronland** [comment]
Let's consider using SSE instead.

**Comment by thisisaaronland** [comment]
Closing because this is so far out of date and there is upcoming work/thoughts involving notifications and BI/pipeline anyway.
