### ISSUE TITLE
Adjust how properties are saved according to wof:controlled

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#205]
See also:
https://github.com/whosonfirst/whosonfirst-properties/commit/594ae028338a8655e849c41b4769532f887e7f35

**Comment by thisisaaronland** [comment]
Some of this will (eventually) be handled automatically by:

https://github.com/whosonfirst/py-mapzen-whosonfirst-hierarchy/blob/master/mapzen/whosonfirst/hierarchy/__init__.py#L41-L62

But it does highlight the need to _set or update_ `wof:controlled` when a user explicitly chooses a parent in the UI.
