### ISSUE TITLE
Set initial geom:latitude and geom:longitude from URL

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#208]
You should be able to click through a link like https://whosonfirst.dev.mapzen.com/boundaryissues/add/#12/37.76915/-122.3584 give it a name and click save. Presently there's an extra step where you have to nudge the pin on the map in order to assign the coordinates.

/cc @burritojustice

**Comment by iandees** [comment]
Bonus points if you don't require a zoom level so that someone could link to the add a venue page with a lat/lon pre-populated. For example, when a venue doesn't exist my Checkin Checker service will send a link to a page to add a POI to OSM at a specified lat/lon (from the Foursquare checkin).

**Comment by dphiffer** [comment]
Ok, this should be fixed now.

@iandees the syntax to link to just a plain lat/lon is like this: https://whosonfirst.dev.mapzen.com/boundaryissues/add/?ll=37.76915,-122.3584
