### ISSUE TITLE
Unable to save venue feature with "minimal set of options"

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#214]
I added information for a new venue record with a minimal set of options through boundary issues, but received this logging error when trying to save the feature:

```
error calling wof.save
```

**Screenshot of logging error:**
<img width="807" alt="screen shot 2017-03-01 at 9 19 58 am" src="https://cloud.githubusercontent.com/assets/18567700/23472129/bb542150-fe60-11e6-92cb-3e6f45bda92f.png">

**Error shown in the console log:**
<img width="933" alt="screen shot 2017-03-01 at 9 19 49 am" src="https://cloud.githubusercontent.com/assets/18567700/23472125/b8d22c42-fe60-11e6-9761-aaf734246c94.png">

**Comment by dphiffer** [comment]
Fixed, thanks @stepps00!
