### ISSUE TITLE
Centroid editor - basic requirements

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#225]
This is mostly a placeholder for now.

* https://github.com/whosonfirst/whosonfirst-geometries/blob/master/README.md#centroids
* `geom:` centroids can not be edited
* Any centroid manually edited should be added to `wof:controlled`
* Figure out something something something about `src:*` properties for centroids (like what is the simplest dumbest thing)

**Comment by thisisaaronland** [comment]
Related: https://groups.google.com/d/msg/iiif-discuss/uVyh3YtA3pU/7RJWAAQ3AAAJ

**Comment by dphiffer** [comment]
Closing this, remaining issues are going into https://github.com/whosonfirst/whosonfirst-www-boundaryissues/milestone/14
