### ISSUE TITLE
Saving a record that has "no pending changes" strips name property values

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#232]
[This commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/38df4246d0561cb54842a87900ec79f4f85e3d6a) contains changes to the record for Melbourne, Australia. 

After viewing the Melbourne record in BI, I hit "Save" (the "no pending changes" message was shown). I made no changes, yet the `name:bel_x_preferred`, `name:eng_x_colloquial`, `name:eng_x_preferred`, `name:jpn_x_preferred`, and `name:kor_x_preferred` property values were stripped away.

Steps to replicate:

- Search for Melbourne, open the locality record [to edit](https://whosonfirst.mapzen.com/boundaryissues/id/101933229/#12/-37.8276/144.9708)
- Click "name" to view existing `eng` name values
- Click the drop-down menu and select a new language
- Click "Save" at the bottom of the page ("no pending changes" should appear below)

The name properties seem to be stripped at random; I only viewed the English and Korean languages, yet the Belarusian and Japanese names were reset, too.

I have a feeling this my be the same cause of name values being stripped out of an [earlier commit that edited St Petersburg](https://github.com/whosonfirst-data/whosonfirst-data/commit/9f361718fdef95895fd26bffc907e3d1d20315ed) (@nvkelso).

**Comment by dphiffer** [comment]
Well, I found the direct cause for the name disappearing (it's repeatable on my local environment), but I'm not totally sure _why_ it's doing it. Basically the page gets built with all the name permutations in the HTML, and those ones seem to be omitted for some reason. So they just aren't on the page at load time.

**Comment by dphiffer** [comment]
Ok, this *should* be fixed on dev. I'm gonna wait until tomorrow to deploy on prod since it's getting kinda late here.

**Comment by nvkelso** [comment]
@dphiffer Was this deployed to `prod`?

**Comment by dphiffer** [comment]
Yeah, it was. Are you seeing this issue again?
