### ISSUE TITLE
Don't clobber wof:tags during CSV stepthrough

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#247]
If you choose to merge an imported record with an existing WOF record, the tags should get combined right after pressing the "same place" button.

**Comment by stepps00** [comment]
Example of a recent commit where the `wof:tags` property is being overwritten instead of appended:

https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ca/commit/a81f0cfd86cef0868b7a0eb84a414a2404c3bb17#diff-5a4ad5b135686ce517d0e07dfae2de10
