### ISSUE TITLE
tried to edit a venue by ID, and it went to the superseded record

### ISSUE THREAD

**Issue by burritojustice** [whosonfirst/whosonfirst-www-boundaryissues#249]
so I am trying to update the thing that superseded Ti Couz in BI. 

It's Giordano Bros and is in there, but really hard to search for (it basically only searches for `Giordano` which returns thousands of results...)

I tried searching its WOF ID, 1108800845, but that just returns Ti Couz which is weird. And I can't fake out BI by trying to build the URL manually:

https://whosonfirst.mapzen.com/boundaryissues/id/1108800845 404s

**Comment by thisisaaronland** [comment]
Appears to be fixed. Prolly just a BI indexing thing.
