### ISSUE TITLE
Geometries of records with a parent_id of -2, -3, or -4 do not display in Spelunker

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#263]
Geometries of records with a `wof:parent_id` value of `-2`, `-3`, or `-4` do not appear in the Spelunker, on their respective pages. 

**Examples:**
- [New York](https://whosonfirst.mapzen.com/spelunker/id/85977539/#9/40.6979/-73.9797)
- [Hartsfield-Jackson Atlanta International Airport](https://whosonfirst.mapzen.com/spelunker/id/102526927/#13/33.6381/-84.4290)

**Comment by dphiffer** [comment]
See also: https://github.com/whosonfirst/whosonfirst-www-spelunker/commit/9668eab8d96388fcfdad50a60c0fc174a25284a8

**Comment by dphiffer** [comment]
A separate but related issue is that we presently don't have a way to configure the Tangram tiles URL to be tiles.dev.mapzen.com. I started a branch over here that isn't quite fully baked yet: https://github.com/whosonfirst/whosonfirst-www-spelunker/tree/dev-config-tiles-url

**Comment by dphiffer** [comment]
Anyway, this should be fixed now.
