### ISSUE TITLE
Empty `mz:categories` property being added to admin records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#265]
Looking at [a recent commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/88eefb489410d32d7de09319de6ec040f5eeb947) in the `whosonfirst-data` repo, the feature `data/101/849/795/101849795.geojson` was edited through Boundary Issues and now includes a `mz:categories: []` property. 

It makes sense to add this property to venue records, but I would not expect this property to be added to admin records like a locality.

**Comment by thisisaaronland** [comment]
If this is really due to (PHP) encoding issues relative to `array()` versus `new StdCls` or whatever it is called, then we should add our own `json_list()` and `json_dictionary()` functions

**Comment by dphiffer** [comment]
See also: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/master/www/include/lib_wof_save.php#L157-L167

**Comment by dphiffer** [comment]
Closing this in favor of #318.
