### ISSUE TITLE
LFS dance not happening for all metafiles

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#273]
Specifically, LFS files are not expanded. For example:

https://github.com/whosonfirst-data/whosonfirst-data/commit/e3047a467ecf99198b96f9a6a87cb69f082ac4d0

**Comment by dphiffer** [comment]
Here are some more details about this pipeline:
https://whosonfirst.dev.mapzen.com/boundaryissues/pipeline/100/

Have you seen any other examples of this happening, @thisisaaronland? It could be helpful for figuring out what they have in common. Right now it's a bit mysterious to me how _some_ but _not all_ meta files don't get handled by LFS properly.

**Comment by thisisaaronland** [comment]
Can you point to the specific problem in that pipeline? The only error I see is that the relevant .git credentials haven't been set ?

**Comment by dphiffer** [comment]
No, I don't see the where problem originated from. My expectation is that LFS would work for all files or for none. The other thing is that since this was one of the early-ish dev pipeline runs, it's possible there was an issue that got worked out.

**Comment by thisisaaronland** [comment]
Okay, well let's just close this until it happens again since neither one of us can remember what the what is...

**Comment by dphiffer** [comment]
Works for me!
