### ISSUE TITLE
Commits to venue-de not being processed/pushed to master

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#276]
For example this is in the Spelunker:

https://whosonfirst.mapzen.com/spelunker/id/1126128689/

But is not in Github:

https://github.com/whosonfirst-data/whosonfirst-data-venue-de/tree/master/data/%20112/612/868/9/1126128689.geojson

https://github.com/whosonfirst-data/whosonfirst-data-venue-de/commits/master

Similarly this which was just added and so maybe wasn't picked up by the cronjob but risks suffering the same fate as 1126128689:

https://whosonfirst.mapzen.com/spelunker/id/1126128697/

**Comment by dphiffer** [comment]
I've identified the problem, which came up before with some previous venues in Canada. The same solution worked here:
- Rebuild hierarchy (to set `wof:country` and `iso:country`, which were incorrectly assigned `US`)
- Fix the `wof:repo` porperty

**Comment by thisisaaronland** [comment]
Is the issue that new records in a non-US context get assigned (by BI) an invalid `wof/iso:country` property which then ripples down to the `wof:repo` property?

**Comment by thisisaaronland** [comment]
Okay, I confirmed that's the issue (BI pre-filling properties incorrectly. I will file a separate ticket.

**Comment by thisisaaronland** [comment]
Re-opening because this still seems to be happening? Specifically:

https://whosonfirst.mapzen.com/spelunker/id/1126128711/
https://whosonfirst.mapzen.com/boundaryissues/id/1126128711

https://github.com/whosonfirst-data/whosonfirst-data-venue-ca/tree/master/data/112/612/871/1/1126128711.geojson

Of note: the record in question was assigned an `iso:country` property of "US" presumably by BI?

Even though the `wof:repo` property was manually assigned a value of "whosonfirst-data-venue-ca" it does not appear to have been picked up by the cron jobs or successfully processed?

I've tweaked and save the `iso:country` property and am waiting to see if subsequent cron jobs do the right thing...

**Comment by thisisaaronland** [comment]
This appears to still be a problem. Updates to `1126128711` described above do not appear to have satisfied the cron jobs.

**Comment by dphiffer** [comment]
Sorry about that, I had disabled cron while I was debugging this. I've reenabled it.

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst-data/whosonfirst-data-venue-ca/commit/f632789c4884f684318d4a52d6ee93a6c73ca636

Manually set all the things correctly and venue was processed as expected.
