### ISSUE TITLE
BI pre-filling wof:country and wof:repo incorrectly for non-US places

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#277]
For example, adding a new venue from `/venue` located in Montreal causes BI to pre-fill the `wof:country` property as "US" and the `wof:repo` property as "whosonfirst-data-venue-us-qc".

Which in turn prevents things from being committed to GH correctly:

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/276

`wof:country` should be derived from the hierarchy and `wof:pip` should assume `whosonfirst-data-PLACETYPE-COUNTY` and then be amended in code (for now) if the country is the "US".

**Comment by dphiffer** [comment]
Confirmed, I can reproduce this one on the venues page.

**Comment by thisisaaronland** [comment]
Also, `iso:country`. Specifically: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/276#issuecomment-310490758

**Comment by dphiffer** [comment]
This should be fixed now. The problem was that it wouldn’t update the country after setting it from the initial map position.

**Comment by thisisaaronland** [comment]
Closing until it happens again (logic is now on the backend).
