### ISSUE TITLE
BI hierarchy code assigns venue as "locality_id" (when there is no locality ?)

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#279]
For example, the Salt Lick which is outside of Austin in a rural area:

https://whosonfirst.mapzen.com/boundaryissues/id/303109123

{"continent_id":102191575,"country_id":85633793,"county_id":102080715,"locality_id":"303109123","region_id":85688753}

Note the lack of a `venue_id` property and the `"locality_id":"303109123"` bit.

Waiting for commit to be processed to see whether this actually gets saved.

**Comment by dphiffer** [comment]
Ack, looking into this.

**Comment by dphiffer** [comment]
Just to leave some bread crumbs of my debug process, I'm seeing the incorrect `locality_id` being returned from the GeoJSON pony:
```
curl "http://localhost:8181/pip?latitude=30.131436&longitude=-98.01646&placetype=venue&wof_id=303109123"
{
  "hierarchy": [
    {
      "continent_id": 102191575, 
      "country_id": 85633793, 
      "county_id": 102080715, 
      "locality_id": "303109123", 
      "region_id": 85688753
    }
  ], 
  "ok": 1, 
  "parents": [
    {
      "Deprecated": false, 
      "Id": 102080715, 
      "Name": "Hays", 
      "Offset": -1, 
      "Placetype": "county", 
      "Superseded": false
    }
  ]
}
```

I'm now looking around here in the code: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/master/services/geojson-server/wof-geojson-server.py#L139

**Comment by dphiffer** [comment]
Oh now I see the bug. The `placetype` variable is getting overridden in the special case just above.

**Comment by dphiffer** [comment]
This should be fixed now. If you try rebuilding the hierarchy it should now omit `locality_id` from the hierarchy.

**Comment by thisisaaronland** [comment]
This is still setting `wof:parent_id` incorrectly but that can be tracked in a separate issue as part of the work to use the newer `mapzen.whosonfirst.hierarchy` code to determine parents and hierarchies.
