### ISSUE TITLE
debug error when trying to edit

### ISSUE THREAD

**Issue by todrobbins** [whosonfirst/whosonfirst-www-boundaryissues#297]
Should I be seeing something different than this when clicking on the edit hand for [https://whosonfirst.mapzen.com/boundaryissues/id/1108472873](https://whosonfirst.mapzen.com/boundaryissues/id/1108472873)?

![screen shot 2017-07-12 at 10 53 44 am](https://user-images.githubusercontent.com/158590/28129422-7ccd6060-66f0-11e7-8688-037b0aad79e1.png)

**Comment by thisisaaronland** [comment]
Interesting. Technically, you should see that link at all (yet :-)

**Comment by todrobbins** [comment]
I'm stay in the bushes for now then 😜
