### ISSUE TITLE
Don't drop existing values when saving

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#32]
See: https://github.com/whosonfirst-data/whosonfirst-data-venue-us-new-york/commit/311770f7366a379a28859e83350b65ec7a9ffa6e
- `iso:country` & `wof:country`
- All array types: `sg:classifiers`, `wof:belongsto`, `wof:breaches`, `wof:hierarchy`, `wof:supersedes`, `wof:superseded_by`

**Comment by dphiffer** [comment]
I took a first pass at this where I [merge new values into the existing record](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/flamework/www/include/lib_wof_save.php#L41-L59), but I've come to realize this is a flawed approach in a different way. It means you effectively cannot delete a property once it exists.

I need the save function call include a "bit mask" of properties that says "these are the ones that got updated."

**Comment by thisisaaronland** [comment]
Tell me more...

**Comment by dphiffer** [comment]
If I remove a property in the UI, the saved key/value hash just doesn't include the property. So the original one will continue existing because of how I'm using `array_merge` to update the existing saved GeoJSON.

I'm thinking now that I should not be saving the _entire_ GeoJSON, but rather those few properties that the UI knows were edited. The reason for _that_ being that it will reduce the likelihood that two people clobber each other's changes. And then maybe just treat `null` values as "delete this."

Example:

```
{
  "properties": {
    "mz:foo": "foo",
    "mz:bar": "bar
  }
}
```

Currently if you remove the first property, what gets sent to the server is this:

```
{
  "properties": {
    "mz:bar": "bar
  }
}
```

... which gets `array_merge`d onto the previous value.... which doesn't end up deleting `mz:foo`.

The new behavior would instead send this to the server:

```
{
  "properties": {
    "mz:foo": null
  }
}
```

Meaning: leave everything else alone, but drop `mz:foo`.

**Comment by dphiffer** [comment]
Another, perhaps simpler, approach is: just adjust the web UI to support _all_ properties.

**Comment by thisisaaronland** [comment]
Well, we will have to support _all_ the properties soon enough so perhaps this is as good a time as any to pull the band-aid off.

What do you imagine being the gotchas doing that now?

**Comment by dphiffer** [comment]
I guess currently there's no way to express **types** for new things that aren't explicitly described in the GeoJSON schema files. If you create a new property, you are currently forced into creating a string property.

And even if we did schema-ify things, I still need to write code to template those schemas for more complex types (like if you're adding a set of objects into an array).

I neatly avoid this with the hierarchy values, since it's not exposed as user-editable properties, which is a tactic I'm fine using elsewhere.

**Comment by thisisaaronland** [comment]
At the risk of bringing a yak in to the room... can we use the ES mappings file to generate the schema files, or vice versa? They are basically the same problem.

With a few exceptions (things that are known WOF IDs) I think I can live with default strings until proven otherwise if it gets us "ALL TEH PROPERTEES" support sooner rather than later.

**Comment by dphiffer** [comment]
Yeah, using the ES schema could be helpful for pulling out typing hints. WOF IDs are probably the main thing—"this should be a number type."

Now that we're supporting array types, a lot of the things that were [dropping previously](https://github.com/whosonfirst-data/whosonfirst-data-venue-us-new-york/commit/311770f7366a379a28859e83350b65ec7a9ffa6e#diff-6ba139b416d8fafb7a7ff3bf4f25a5f4L35) are now being included. So that's good. Maybe the one complex case I've seen that isn't accounted for is `sg:classifiers`. It's an array of objects like `{ "category": "...", "subcategory": "...", "type": "..." }`. Maybe just handle these one-offs as they come along?

**Comment by thisisaaronland** [comment]
Yeah, WOF IDs and booleans. As in:

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/40

The SG classifiers stuff should just be dealt with in the simplest/dumbest way which possibly includes read-only unless it needs to be deleted. We will probably use those values as starter data but otherwise it's going to quickly be replaced or made redundant with WOF data.
