### ISSUE TITLE
Pipeline tasks stuck on "Pipeline is waiting"

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#327]
I opened a pipeline last Friday ([here](https://whosonfirst.mapzen.com/boundaryissues/pipeline/289)), which never passed the "Pipeline is waiting" phase. I cancelled that pipeline task today and opened a new one ([here](https://whosonfirst.mapzen.com/boundaryissues/pipeline/304/)), hoping that would resolve the issue, but the new pipeline task is also stuck on the same phase. 

Screenshot below:

<img width="743" alt="screen shot 2017-08-28 at 5 02 15 pm" src="https://user-images.githubusercontent.com/18567700/29798595-b7ee1738-8c12-11e7-9266-35a140e2e70d.png">

This is a "merge_pr" pipeline task; I have not checked if this issue occurs with the "meta_files" pipeline tasks.

**Comment by dphiffer** [comment]
The pipeline switch was mistakenly left in the "off" position. Sorry about that!
