### ISSUE TITLE
Sporatic "Missing or invalid crumb" errors

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-boundaryissues#338]
Seemingly resolves itself after reloading the page, but wtf?

**Comment by thisisaaronland** [comment]
I can confirm I've been seeing these too.

**Comment by dphiffer** [comment]
Ran `sudo ntpdate time.nist.gov` on the server, in case it's a time drift issue.

**Comment by dphiffer** [comment]
Continued issues leads me to believe the cause was not time drift.

**Comment by dphiffer** [comment]
I tracked this down. The cause was that `$GLOBALS['_SERVER']['REMOTE_ADDR']` contained the IP address of the ELB instead of the client IP.

**Comment by thisisaaronland** [comment]
Yeah, you don't want to use that. You should use the `remote_addr` function: 

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/master/www/include/init.php#L113-L122

**Comment by dphiffer** [comment]
Hmm that gives me back `192.168.18.245` on dev. I wonder if we need to tinker with how the headers are set upstream?

**Comment by thisisaaronland** [comment]
It's possible we're passing a different header. I would start with the proxy configs.

**Comment by dphiffer** [comment]
Pretty sure this is fixed now.
