### ISSUE TITLE
Add wof:placetype_alt to the schema

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#339]
This property should be catalogued as a list (not a string). Example:

```
"wof:placetype_alt":[
    "county", 
    "localadmin"
],
```

**Comment by thisisaaronland** [comment]
wait, what? that’s going to break a bunch of code - what is the rationale for a list? are these just quantum places?

**Comment by stepps00** [comment]
This is follow-up to our conversation about the `wof:placetype_alt` property. We should ensure the `wof:placetype_alt` property is a list, rather than a string. Because a record can have multiple alt placetypes, we should use:

```
"wof:placetype_alt":[
    "county", 
    "localadmin"
],
```

rather than..

```
"wof:placetype_alt":"country, localadmin"
```
