### ISSUE TITLE
Unable to download descendant records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#342]
I am unable to retrieve a bundled set of descendant records from the bundler tool.

**Steps to repeat:**

1. Go to https://whosonfirst.mapzen.com/spelunker/download/85633789/?exclude=nullisland
2. Click the box next to "region (20)"
3. Click "Start Bundle"

You should see the following error message:

```
Error: connection failed [object ProgressEvent] (999)
```

**Screenshot:**

<img width="972" alt="screen shot 2017-11-01 at 3 36 51 pm" src="https://user-images.githubusercontent.com/18567700/32301385-fa79bc66-bf1a-11e7-8dfe-c54ad5d90e26.png">

**Comment by dphiffer** [comment]
My initial read on it is this looks like a CORS issue.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://places.mapzen.com/?api_key=(snip). (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by dphiffer** [comment]
I think I found the source of the problem. It wasn't CORS after all. Instead, it seems that requests are going to the wrong endpoint. Until I get a fix in I've disabled the bundler feature.

**Comment by dphiffer** [comment]
Turned out to be a config file issue. Ran `opzworks berks` and redeployed, and now it should be back to working.
