### ISSUE TITLE
Error: The number of items in your bundle (0) does not match...

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#351]
I am unable to download descendant bundles from Boundary Issues. Error message:

`The number of items in your bundle (0) does not match the expected 20.`

Steps to replicate:
1. Navigate to https://whosonfirst.mapzen.com/spelunker/download/85672195/?exclude=nullisland
2. Click the box next to " county 20"
3. Click the "Start Download" button
4. Notice the error message "The number of items in your bundle (0) does not match the expected 20."

Console message: "Failed to load resource: the server responded with a status of 404 (NOT FOUND)"

Chrome Version 62.0.3202

**Comment by dphiffer** [comment]
Weird, it looks like the Mapzen Places API is returning no results:
```
$ curl "https://places.mapzen.com/v1?method=whosonfirst.places.getDescendants&api_key=(snip)&id=85672195&placetype=county"
{"places":[],"next_query":null,"total":0,"page":1,"per_page":100,"pages":0,"cursor":null,"stat":"ok"}
```

**Comment by stepps00** [comment]
@dphiffer - confirming this is fixed :tada:

**Comment by dphiffer** [comment]
Hooray! I will close.
