### ISSUE TITLE
name:* fields need to be arrays

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#41]
See attached.

![screen shot 2016-03-18 at 17 03 16](https://cloud.githubusercontent.com/assets/12658759/13895021/b1ae90f0-ed2b-11e5-9452-5ce500fc9329.png)

**Comment by thisisaaronland** [comment]
This appears to be done on the back-end but still needs some finessing on the front end? Specifically issue #148 

@dphiffer can you confirm/deny, please.

![screen shot 2016-07-29 at 08 30 32](https://cloud.githubusercontent.com/assets/12658759/17253769/fe7e9e5e-5566-11e6-8053-153e45c2ce38.png)

**Comment by dphiffer** [comment]
Confirmed! This needs a better UI.
