### ISSUE TITLE
Hierarchies not being saved for the Jell-O Museum

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#49]
WOF ID 336913797

No, really... http://www.jellomuseum.org/

![screen shot 2016-03-18 at 21 37 31](https://cloud.githubusercontent.com/assets/12658759/13896660/a4871fa2-ed51-11e5-8d6d-2476c8bd5d0b.png)

**Comment by dphiffer** [comment]
Ah, looks like the parent, [Fort Hill](https://whosonfirst.mapzen.com/spelunker/id/420528737/), has no hierarchy. I'll update the JS to be more accommodating in this situation.
