### ISSUE TITLE
Colour dots on map based on their mz:is_current / edtf:deprecated status

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#57]
Keep in sync with the BI CSS file:

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/flamework-thisisaaronland/www/css/mapzen.boundaryissues.css#L167-L201

**Comment by thisisaaronland** [comment]
This is good, but leaving open because the colours on the map are too muted. See attached.

![screen shot 2016-03-21 at 18 12 30](https://cloud.githubusercontent.com/assets/12658759/13939258/afbf7450-ef90-11e5-94cd-a559fcfc290b.png)
![screen shot 2016-03-21 at 18 13 31](https://cloud.githubusercontent.com/assets/12658759/13939257/afbf50ce-ef90-11e5-9e49-bc43020e06a6.png)

**Comment by dphiffer** [comment]
Yeah, agreed. I'll take a shot at updating the colors to stand out more.

**Comment by dphiffer** [comment]
Are these good assumptions?
- Closed & deprecated venues should be de-emphasized (perhaps set to gray)
- Those marked current and unknown status should be emphasized and obviously distinct

Or should all statuses be equally visible? What about `mz:is_funky`, should those have a third emphasized/distinct color?

**Comment by thisisaaronland** [comment]
Let's start with glaring, explicit colours and then dial it back as people get used to things. In the beginning the important bits will be need to see the difference between things that have been attended to (marked as current or not) and things that need to be addressed.

Maybe ask Geraldine for the hot fluorescent colours in the her new map book :D

**Comment by dphiffer** [comment]
For now I'm just going with the colors from Bootstrap, since they're already convenient to apply to buttons, etc. I also switched the outline stroke color from black, to make them show up a bit more.
https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/0055a39edc2e5fe7853369cc07d3d59790921d95
