### ISSUE TITLE
The Cooper Hewitt is not in Brooklyn

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#58]
WOF ID : 420571601 (lists the localadmin as Brooklyn)

Is this a PIP thing or... ?

What are the UI / UX  hoohah necessary to fix this and make those changes stick across edits?

**Comment by riordan** [comment]
Manhattan is in Brooklyn.

Tres Brooklyn.

**Comment by dphiffer** [comment]
My thoughts on this are: we need a good way to queue up offline tasks. Same goes for pulling in changes via `git pull`.

**Comment by thisisaaronland** [comment]
At this point, Gearman is the definition of "old and boring" technology so we should start there.

**Comment by thisisaaronland** [comment]
Closing because this issue is really this issue: https://github.com/whosonfirst/whosonfirst-data/issues/238
