### ISSUE TITLE
Please to follow the indenting/formatting conventions

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#70]
https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/flamework/www/geojson.php

8-space tabs, leading indent (tab) for all the things.

**Comment by dphiffer** [comment]
Got it.

Also: the first part seems to imply we should use tabs for alignment. (As in the .htaccess rules.) But I've seen a mix of spaces and tabs for indenting. Should I be tending one way or the other?

**Comment by thisisaaronland** [comment]
This is the part where Cal makes scowl-y face at me because I use Emacs and Emacs and whitespace and tabs is a world of pain and stupid and often the mix-up is my fault :-(

If there is whitespace that should be considered "the wrong way". Tabs, FTW.

**Comment by dphiffer** [comment]
I don't have strong feelings about it, anything different from what you currently write in your own dev environment looks _wrong_, until you change to a new style and the old way looks completely wrong. I've changed styles so many times I've lost count.

Presently I'm on a tabs-for-indenting-spaces-for-alignment kick, but mostly I'm just happy to not be adding [all the extra spaces between parens that WordPress suggests](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style). The leading tab thing doesn't bother me at all, I just haven't gotten into the habit for new files.

Just to be clear: we should be using tabs for indenting, yeah? (Your last sentence could be read two different ways.)

**Comment by thisisaaronland** [comment]
Tabs for indenting :-)
