### ISSUE TITLE
Procedures for re-indexing without blowing away the db

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#77]
https://github.com/whosonfirst/whosonfirst-www-boundaryissues/wiki/Updating-ES-schema

Reloading the schema has the side-effect of purging the index.

**Comment by dphiffer** [comment]
See: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/wiki/Updating-ES-schema
