### ISSUE TITLE
Updates are creating new records?

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#78]
```
diff -uw data/420/780/085/420780085.geojson data/420/780/089/420780089.geojson
--- data/420/780/085/420780085.geojson  2016-03-24 01:44:13.949267155 +0000
+++ data/420/780/089/420780089.geojson  2016-03-24 01:44:13.949267155 +0000
@@ -1,5 +1,5 @@
 {
-  "id": 420780085,
+  "id": 420780089,
   "type": "Feature",
   "properties": {
     "addr:website":"http://www.abraconyc.com/",
@@ -35,11 +35,11 @@
             "locality_id":85977539,
             "neighbourhood_id":85816887,
             "region_id":85688543,
-            "venue_id":420780085
+            "venue_id":420780089
         }
     ],
-    "wof:id":420780085,
-    "wof:lastmodified":1458777517,
+    "wof:id":420780089,
+    "wof:lastmodified":1458410984,
     "wof:name":"Abra\u00e7o",
     "wof:parent_id":85816887,
     "wof:placetype":"venue",

$> php -r 'echo date("c",1458777517);'
2016-03-23T23:58:37+00:00

$> php -r 'echo date("c",1458410984);'
2016-03-19T18:09:44+00:00
```

https://github.com/whosonfirst-data/whosonfirst-data-venue-us-new-york/commit/e7e38b3c0ab7c435158d72113600282fcc4a4179

https://github.com/whosonfirst-data/whosonfirst-data-venue-us-new-york/commit/93e9b85c3465152a421d9e7e2b69e654f8f9e3d3

See also, attached screenshot - the weird part is that of the two Shanghai Cafe (100 Mott) records only one has actually been checked in (420780343, and not 420780341).

It is probably worth adding a lock / semaphore to the local JS to prevent it from triggering the save button _during_ a save?

![screen shot 2016-03-23 at 19 03 40](https://cloud.githubusercontent.com/assets/12658759/14006527/50130a48-f12b-11e5-9aa1-4773f2f0a8be.png)

**Comment by dphiffer** [comment]
I am not 100% sure how this might have happened, but I have some theories that involve bits of code that have since been improved. The short version is that a lot of things that used to happen in PHP are now done in Python, more reliably. But I definitely like the idea of the flag to prevent triggering a save during a save (see: https://github.com/whosonfirst/whosonfirst-www-boundaryissues/commit/0f9ee97ce2938a598fc55b3a2b0eea40b039099c).
