### ISSUE TITLE
ES index not updating?

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#80]
It appears as though the ES index is not getting updated correctly. For example setting `is_current=0` on a record still causes that record to appear on `/current/

**Comment by dphiffer** [comment]
I am tempted to say this was just the result of early testing, when I hadn't quite gotten ES working yet. But just now when I tried pressing [this is closed] on [a record](https://52.91.189.86/id/421205905/) I got an error message `[400] Error saving via GeoJSON service:`, which is not very descriptive, and also not updating ES index. The log says `2016-04-06T14:20:08.581Z error [object Object]` which also doesn't reveal a whole lot.

**Comment by dphiffer** [comment]
In summary:
- fix the thing that's causing the GeoJSON 400 error
- improve error logging
- double check ES is getting updated

**Comment by dphiffer** [comment]
- it was file permissions
- error logging is fixed
- ES index is updating! \o/
