### ISSUE TITLE
touched by a human dot json

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#85]
This is not specifically a Boundary Issues problem (it affects all of WOF) but I am going to put it here since it has the chance to get addressed sooner than later. It might best be addressed in `py-mapzen-whosonfirst-export` but I am not sure yet...
## 

Here is the output from a dry-run of a script to update venues per https://github.com/whosonfirst/whosonfirst-data/issues/238 :

```
[420573497][Angel's Share] 40.729783, -73.989261 -> 85816887 (85816887)
parent East Village (neighbourhood)
[420573499][Miles] 40.701618, -73.927066 -> -1 (85977539)
[420690417][Warren 77] 40.713875, -74.007597 -> -1 (85865713)
[420777821][Toshi's Living Room] 40.743934, -73.989143 -> -1 (85892937)
[420777823][VBar] 40.729552, -73.999583 -> 420529189 (420529189)
parent Greenwich Village (neighbourhood)
[420777827][Toast] 40.814767, -73.959349 -> -1 (85865545)
```

The relevant bit is `-> -1 (85865545)` which means that the parent ID for that location will be set to be `-1` where before it was `85865545`. This is probably because there are overlapping parents and there is no way to choose.

The example above is pulling from venues in NY state so I know the reason that there is a parent ID is because an explicit choice was made. I also know that I can probably write some code (in whosonfirst-toolbox/script/ssue-238-venues.py) to test the results and try to do the right thing in this instance.

But.

We should start to track things in a corresponding `WOFID-touched-by-a-human.json` (or whatever) file that can be consulted for when / where it is appropriate for a robot to update an existing value.

@dphiffer – I am going to assign this to you to start, because it seems easy enough (he said...) to simply write changes to disk on save/edit.

We will probably juggle this ticket back and forth as we go and depending on the demands of other things. Have a crack at wiring this up to the current BI code and report back!

**Comment by thisisaaronland** [comment]
Oh, the part I left out is:

This should basically be a straight mirror of the WOFID.geojson file in terms of structure. That is if I need to know whether `foo.bar.baz` can be updated I should simply be able to check for it's presence (as `foo.bar.baz`) in WOFID-tbh.json.

**Comment by thisisaaronland** [comment]
Related: https://github.com/whosonfirst/py-mapzen-whosonfirst-diff

**Comment by dphiffer** [comment]
Sounds good! It's worth mentioning that the very earliest Boundary Issues code produced WOF records that may need some manual clean up.

**Comment by thisisaaronland** [comment]
Example: wof-data:data/102/112/179/102112179-tbh.json
