### ISSUE TITLE
It’s hard to immediately tell what’s a form field

### ISSUE THREAD

**Issue by migurski** [whosonfirst/whosonfirst-www-boundaryissues#93]
In views like this, it’s not clearly obvious that the underlined blank areas can be typed in:

<img width="393" alt="screen shot 2016-04-04 at 8 39 08 pm" src="https://cloud.githubusercontent.com/assets/58730/14268110/68ee65fc-faa5-11e5-93ef-8b264225b0dc.png">

Consider removing custom CSS from these, so they look browser-native?

**Comment by dphiffer** [comment]
Coming soon: more "fieldy" looking fields.
<img width="619" alt="screen shot 2016-04-06 at 10 27 21 am" src="https://cloud.githubusercontent.com/assets/38114/14320997/5fd5d306-fbe5-11e5-8ce2-0d392cc88d70.png">

**Comment by migurski** [comment]
mmmmm fieldy
