### ISSUE TITLE
Key-value removal UI introduces two kinds of confusion

### ISSUE THREAD

**Issue by migurski** [whosonfirst/whosonfirst-www-boundaryissues#94]
I’m seeing two possibly-confusing features on the key-value elements:
1. The “x” appears only when rolled-over, which makes it somewhat mystery-meat.
2. Once clicked, the item instantly disappears. It could instead remain on the page, visually “deleted” in some way such as a strike-through.

<img width="402" alt="untitled2" src="https://cloud.githubusercontent.com/assets/58730/14268134/addf5d38-faa5-11e5-95b8-012c5bc42b65.png">

**Comment by dphiffer** [comment]
Thanks, this is helpful input!

**Comment by thisisaaronland** [comment]
Closing as the properties now have explicit not-magic "remove" controls for properties.
