### ISSUE TITLE
Add wof_can_edit($user) 

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-boundaryissues#95]
Or equivalent. Basically something that is not just a "is user logged in" check. Related:

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/43

**Comment by migurski** [comment]
Aaron asked to add this here:
1. Logged in with Github
2. Went to https://52.91.189.86/id/370165697/
3. Modified title “Poo Man” to “Poo Men”
4. Hit “save”
5. Got the “Saved” text back below the button
6. Reloaded and saw “Poo Men” as I expected (?)
7. Aaron said the change was not represented in Github
8. Hard-refreshed and still saw “Poo Men” in the title

**Comment by thisisaaronland** [comment]
Taking this one to write the code and then to hand it back to @dphiffer to do template wrangling etc.

**Comment by thisisaaronland** [comment]
See also: issue #194

**Comment by dphiffer** [comment]
See: [lib_users_acl.php](https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/master/www/include/lib_users_acl.php)
