### ISSUE TITLE
Github sign-in loses original link

### ISSUE THREAD

**Issue by migurski** [whosonfirst/whosonfirst-www-boundaryissues#96]
Starting at https://52.91.189.86/id/370165697/, I am redirected to Github OAuth, which performs several other redirects and drops me at https://52.91.189.86/. I expected to end up at https://52.91.189.86/id/370165697/.

**Comment by thisisaaronland** [comment]
Yeah, that's a Flamework thing ultimately. I will try to fix that this week... or I will just the CH people to send me the fix I wrote two (three?) years ago...

**Comment by thisisaaronland** [comment]
Not tested yet, but:

https://github.com/whosonfirst/flamework-sso-github/tree/redir

**Comment by thisisaaronland** [comment]
Fixed. Waiting on PR.
